#!/usr/bin/perl -w
#$Id$

crash !

The script will be removed in the next AA release (for security reasons with readfile())
Just checking, if it is not used anymore.
If you need this script, write me on actionapps@ecn.cz
Honza Malik, 2012-02-10



# NOTE: you need to change these vriables
$host  = ''; # like 'http://127.0.0.1';
$cachedir= '/tmp/cache';
$cache4days = '.1'; # '.1' caches for 2.4 hours
if (! $host ) die "Error -- you need to set \$host";

use LWP::UserAgent;

# Index:
# 1. usage
# 2. build URL
# 3. figure out if the cachefile exists for this URL
# 4. if the cachefile does not exist or is not new enough,
#    run the query, cache the result, and print the result
# 5. else, print the cached version

# -------------------------------------------------
# 1. usage

# if this is not called as a webpage, produce usage statement
if ( ! $ENV{PATH_INFO} ) {

    print <<ENDOFHELP
=================================================
scriptname: remotec
  Include the output of a script on a remote server into a local webpage.
  Cache the output, and use it again until it expires

author    : madebeer\@igc.org
license   : released GPL - see http://www.gnu.org/license.html

=================================================
Strategic usage:

  The ActionApps is an easy-to-use content-management system.
    http://www.apc.org/actionapps/

  Imagine a nonprofit wants to start using this system for the news section of
  their site, but does not want to move their site to a webhost that has
  action applications installed.

  The webmaster could:
   1. Ask a server with the action applications to setup a slice for them
   2. Include their news items from their slice with 'remote', pulling
      these items into news.html, on their local webhost.

  Note: For high performance, frequently updated sites, set
   \$cache4days = '.01'; # about 15 minutes
  and then have a cronjob visit the page every 10 minutes
  to keep the cache relevant.
  0,10,20,30,40,50 * * * lynx -dump http://www./page.html > /dev/null

  Note: if you and the remote server have excellent bandwidth
        to each other, you may want to use 'remote' to not use
        caching.

=================================================
Technical usage:

Look at the top of this script, and set the variables there.
Make sure cachedir is writable by the webserver

'remotec' is used as an SSI inside an html page.
For example, if you wanted to include the page
   http://www.gn.apc.org/slice.php3
And your page was not on www.gn.apc.org, you would put this
HTML code in your page (setting the \$host variable first):
   <!--#include virtual="/cgi/remotec/slice.php3"-->

'remote' only works with GET (not POST) commands.
You can use URL parameters, like:
<!--#include
       virtual="/cgi-bin/remotec/apc-aa/view.php3?vid=11&als[MY_ALIAS]=3"-->

ENDOFHELP
    ;
    exit;
}

# -------------------------------------------------
# 2. build URL

# we need a the next line, or get an HTTP error.
# it goes first, so if there is an error, we see it in the web browser
print "Content-type:text/html\n\n";

# build the URL of the page we are going to request
$path  = $ENV{PATH_INFO};
$query = $ENV{QUERY_STRING};
$url = $host . $path . "?$query";

# -------------------------------------------------
# 3. figure out if a recent cache exists for this URL

# The cachefile will be  "$cachedir/$url_hashed"
# $url_hashed is an MD5 hash of the $url
# We hash the URL to get a unique name for each URL, that
# we can trust does not have any bad meta-characters

use Digest::MD5  qw(md5_hex);
$url_hashed = md5_hex($url);
die "unexpected character in url_hashed" if ($url_hashed) =~ /\W/;
$cachefile = "$cachedir/$url_hashed";
$nocache = (! -s $cachefile) or (-M $cachefile > $cache4days) ? 1 : 0;

# -------------------------------------------------
# 4. if the cachefile does not exist or is not new enough,
# run the query, cache the result, and print the result

# add UserAgent object, which has ability to send HTTP requests
my $ua = new LWP::UserAgent;
my $res;

if ( $nocache ) {
  $res = $ua->request(HTTP::Request->new(GET => $url));
  if ( $res->is_success() ) {
    open CACHE, '>'.$cachefile or die "could not open $cachefile";
    print CACHE $res->content;
    close CACHE or die "could not close $cachefile";
    print $res->content;
  } else {
    print "<HR>error in from script: $0<BR>Trying to get $url. Result was:",
      $res->content, "<HR>";
  };
} else {

  # -------------------------------------------------
  # 5. else, print the cached version

  $\='';
  open CACHE, $cachefile or die "could not open $cachefile";
  print <CACHE>;
  close CACHE or die "could not close $cachefile";

}
__END__
#$Log: remotec,v $
#Revision 1.4  2005/06/03 00:36:33  honzam
#strings in AA uses "ActionApps" name instead of "APC Action Apps"
#
#Revision 1.3  2001/10/19 06:46:48  madebeer
#added checks for $host
#
#Revision 1.2  2001/10/19 06:44:39  madebeer
#nulled out $host variable, for security reasons
#
#Revision 1.1  2001/10/19 06:16:44  madebeer
#added helper scripts - different versions of remote.
#remote allows remote servers to use apc-aa content in SSIs
#
