<?php
# $Id$
# Language: CZ
# This file was automatically created by the Mini GetText environment
# on 11.10.2002 17:36

# Do not change this file otherwise than by typing translations on the right of =

# Before each message the places where it was used are noted.
# Look there if you are not sure how to translate it.

$mgettext_lang = "cz";

# Unused messages
$_m["Send password"]
  = "Poslat heslo";
# End of unused messages

# c:/apache/htdocs/aa_jakub/misc/alerts/add_user_collection.php3, row 46
$_m["Error - user was not subscribed"]
  = "Chyba - uživatel nebyl zapsán";

# c:/apache/htdocs/aa_jakub/misc/alerts/add_user_collection.php3, row 53
$_m["Missing required info"]
  = "Chybí požadovaný údaj";

# c:/apache/htdocs/aa_jakub/misc/alerts/add_user_collection.php3, row 67
$_m["Howoften set wrong"]
  = "\"Jak èasto\" je nastaveno špatnì";

# c:/apache/htdocs/aa_jakub/misc/alerts/add_user_collection.php3, row 75
$_m["Wrong collection ID"]
  = "Špatné ID kolekce";

# c:/apache/htdocs/aa_jakub/misc/alerts/add_user_collection.php3, row 102
$_m["You have been successfully subscribed to AA Alerts for %1."]
  = "Byl(a) jste úspìšnì zapsán(a) do Zasílání zpráv pro %1.";

# c:/apache/htdocs/aa_jakub/misc/alerts/add_user_collection.php3, row 110
$_m["You must first confirm your subscription (see confirmation e-mail) or subscribe again on %1 in order to receive e-mail Alerts."]
  = "Nejdøíve musíte potvrdit své pøihlášení (viz potvrzovací e-mail) nebo se znovu pøihlásit na %1, abyste mohl(a) dostávat zprávy.";

# c:/apache/htdocs/aa_jakub/misc/alerts/add_user_collection.php3, row 113
# c:/apache/htdocs/aa_jakub/misc/alerts/alerts.php3, row 210
$_m["You can change your subscriptions on %1."]
  = "Své objednávky mùžete zmìnit na %1.";

# c:/apache/htdocs/aa_jakub/misc/alerts/alerts.php3, row 181
$_m["AA Alerts - daily digest of "]
  = "Zasílání zpráv - denní souhrn ";

# c:/apache/htdocs/aa_jakub/misc/alerts/alerts.php3, row 182
$_m["AA Alerts - weekly digest of "]
  = "Zasílání zpráv - týdenní souhrn ";

# c:/apache/htdocs/aa_jakub/misc/alerts/alerts.php3, row 183
$_m["AA Alerts - monthly digest of "]
  = "Zasílání zpráv - mìsíèní souhrn ";

# c:/apache/htdocs/aa_jakub/misc/alerts/confirm.php3, row 38
$_m["Congratulations. Your subscription is finished."]
  = "Blahopøejeme. Dokonèil(a) jste své pøihlášení.";

# c:/apache/htdocs/aa_jakub/misc/alerts/confirm.php3, row 42
$_m["Your code is not valid any more. Please subscribe again."]
  = "Váš kód již není platný. Pøihlašte se prosím znovu.";

# c:/apache/htdocs/aa_jakub/misc/alerts/confirm.php3, row 48
$_m["Subscribe to E-mail Alerts"]
  = "Pøihlašte se k Zasílání zpráv";

# c:/apache/htdocs/aa_jakub/misc/alerts/confirm.php3, row 53
$_m["Finish your subscription to AA Alerts"]
  = "Dokonèete pøihlašování k Zasílání zpráv";

# c:/apache/htdocs/aa_jakub/misc/alerts/confirm.php3, row 56
$_m["The code given is not OK. Please try it again. Don't use any spaces."]
  = "Zadaný kód není správný. Prosím zkuste ho zadat znovu. Nepište mezery.";

# c:/apache/htdocs/aa_jakub/misc/alerts/confirm.php3, row 60
# c:/apache/htdocs/aa_jakub/misc/alerts/subscribe.php3, row 58
$_m["Submit"]
  = "Odeslat";

# c:/apache/htdocs/aa_jakub/misc/alerts/index.php3, row 37, 48
$_m["This email is not registered with Alerts."]
  = "Tento email není pøihlášen k Zasílání zpráv.";

# c:/apache/htdocs/aa_jakub/misc/alerts/index.php3, row 41
$_m["OK. Confirmation email was sent."]
  = "OK. Potvrzovací email byl poslán.";

# c:/apache/htdocs/aa_jakub/misc/alerts/index.php3, row 51
$_m["You have not yet confirmed your subscription. See confirmation e-mail or use Send confirmation."]
  = "Ještì jste nepotvrdil(a) pøihlášku. Podívejte se do potvrzovacího emailu nebo použijte Zaslat potvrzení.";

# c:/apache/htdocs/aa_jakub/misc/alerts/index.php3, row 60
$_m["Wrong password."]
  = "Špatné heslo";

# c:/apache/htdocs/aa_jakub/misc/alerts/index.php3, row 65
$_m["Login to Alerts sending"]
  = "Pøihlašte se k Zasílání zpráv";

# c:/apache/htdocs/aa_jakub/misc/alerts/index.php3, row 71
$_m["Login to Personal settings for Alerts sending"]
  = "Pøihlašte se k osobnímu nastavení Zasílání zpráv";

# c:/apache/htdocs/aa_jakub/misc/alerts/index.php3, row 82
$_m["New user? Subscribe!"]
  = "Nový uživatel? Pøihlašte se!";

# c:/apache/htdocs/aa_jakub/misc/alerts/index.php3, row 84
# c:/apache/htdocs/aa_jakub/misc/alerts/subscribe.php3, row 53
$_m["E-mail"]
  = "E-mail";

# c:/apache/htdocs/aa_jakub/misc/alerts/index.php3, row 86
# c:/apache/htdocs/aa_jakub/misc/alerts/subscribe.php3, row 55
$_m["Password"]
  = "Heslo";

# c:/apache/htdocs/aa_jakub/misc/alerts/index.php3, row 89
$_m["Login"]
  = "Vstoupit";

# c:/apache/htdocs/aa_jakub/misc/alerts/index.php3, row 90
$_m["Login by your e-mail address. If you don't use password, leave that box empty. If you forgot your password, click here and we will send a new confirmation e-mail to you."]
  = "Pøihlašte se pomocí e-mailové adresy. Pokud nepoužíváte heslo, nechte jeho okénko prázdné. Pokud jste heslo zapomnìli, klepnìte zde a my vám pošleme nový potvrzovací e-mail.";

# c:/apache/htdocs/aa_jakub/misc/alerts/index.php3, row 91
$_m["Send confirmation"]
  = "Zaslat potvrzení";

# c:/apache/htdocs/aa_jakub/misc/alerts/user_filter.php3, row 39
$_m["Your session has expired. Please login again."]
  = "Vaše relace vypršela. Pøihlaste se prosím znovu.";

# c:/apache/htdocs/aa_jakub/misc/alerts/user_filter.php3, row 66
$_m["Passwords differ. Please try again."]
  = "Hesla se liší. Zkuste to prosím znovu.";

# c:/apache/htdocs/aa_jakub/misc/alerts/user_filter.php3, row 115, 125
$_m["AA Alerts"]
  = "Zasílání zpráv";

# c:/apache/htdocs/aa_jakub/misc/alerts/user_filter.php3, row 131
$_m["Welcome, %1"]
  = "Dobrý den! Uživatel: %1";

# c:/apache/htdocs/aa_jakub/misc/alerts/user_filter.php3, row 137
$_m["Language"]
  = "Jazyk";

# c:/apache/htdocs/aa_jakub/misc/alerts/user_filter.php3, row 142
$_m["First name"]
  = "Køestní jméno";

# c:/apache/htdocs/aa_jakub/misc/alerts/user_filter.php3, row 144
$_m["Last name"]
  = "Pøíjmení";

# c:/apache/htdocs/aa_jakub/misc/alerts/user_filter.php3, row 147
$_m["Change"]
  = "Zmìnit";

# c:/apache/htdocs/aa_jakub/misc/alerts/user_filter.php3, row 152
$_m["New password"]
  = "Nové heslo";

# c:/apache/htdocs/aa_jakub/misc/alerts/user_filter.php3, row 154
$_m["Retype password"]
  = "Potvrïte heslo";

# c:/apache/htdocs/aa_jakub/misc/alerts/user_filter.php3, row 157
$_m["Change password"]
  = "Zmìnit heslo";

# c:/apache/htdocs/aa_jakub/misc/alerts/user_filter.php3, row 204
$_m["Subscribed Collections"]
  = "Objednané Kolekce";

# c:/apache/htdocs/aa_jakub/misc/alerts/user_filter.php3, row 231
# c:/apache/htdocs/aa_jakub/misc/alerts/util.php3, row 161, 231
$_m["Filter"]
  = "Filtr";

# c:/apache/htdocs/aa_jakub/misc/alerts/user_filter.php3, row 232, 273, 304
# c:/apache/htdocs/aa_jakub/misc/alerts/util.php3, row 221
$_m["How often"]
  = "Jak èasto";

# c:/apache/htdocs/aa_jakub/misc/alerts/user_filter.php3, row 235
# c:/apache/htdocs/aa_jakub/misc/alerts/util.php3, row 222
$_m["unsubscribe"]
  = "zrušit odbìr";

# c:/apache/htdocs/aa_jakub/misc/alerts/user_filter.php3, row 265, 282
$_m["Add"]
  = "Pøidat";

# c:/apache/htdocs/aa_jakub/misc/alerts/user_filter.php3, row 272
$_m["Add predefined collection"]
  = "Pøidejte pøeddefinovanou kolekci";

# c:/apache/htdocs/aa_jakub/misc/alerts/user_filter.php3, row 303
$_m["Add predefined filter"]
  = "Pøidat pøeddefinovaný filtr";

# c:/apache/htdocs/aa_jakub/misc/alerts/user_filter.php3, row 326
$_m["Sign out"]
  = "Odhlásit se";

# c:/apache/htdocs/aa_jakub/misc/alerts/subscribe.php3, row 34
$_m["An email with subscription informations was sent to you."]
  = "Email s pøihlašovacími informacemi vám byl zaslán.";

# c:/apache/htdocs/aa_jakub/misc/alerts/subscribe.php3, row 38, 44
$_m["Subscribe to AA Alerts"]
  = "Pøihlašte se k Zasílání zpráv";

# c:/apache/htdocs/aa_jakub/misc/alerts/subscribe.php3, row 51
$_m["We will send an e-mail message to the address given. Follow the instructions in it to complete your subscription."]
  = "Na zadanou adresu pošleme e-mail. Následujte instrukce v nìm obsažené k dokonèení pøihlášení.";

# c:/apache/htdocs/aa_jakub/misc/alerts/admin_mails.php3, row 73
$_m["Please confirm your subscription"]
  = "Prosím potvrïte svou pøihlášku";

# c:/apache/htdocs/aa_jakub/misc/alerts/admin_mails.php3, row 83
$_m["<p>Hello,</p><p>you didn't yet confirm your subscription to AA Alerts. You can't receive any emails until you do so. \n"
   ."                Please click on URL:</p>%1<p>or copy the URL to your web browser. \n"
   ."             The confirmation is done in order that we can see you did not subscribe by mistake and your e-mail is working.</p><p>Yours<br>&nbsp; &nbsp; &nbsp;APC Alerts moderators</p>"]
  = "<p>Dobrý den,</p><p>nepotvrdil(a) jste své pøihlášení do Zasílání zpráv. \n"
   ."     Nemùžete dostávat e-maily, dokud tak neuèiníte. \n"
   ."                Klepnìte prosím na URL:</p>%1<p>nebo URL zkopírujte do svého webového prohlížeèe. \n"
   ."             Potvrzení se vyžaduje proto, abychom vìdìli, že nejste pøihlášen(a) omylem a že Váš e-mail funguje.</p><p>Vaši<br>&nbsp; &nbsp; &nbsp;moderátoøi Zasílání zpráv</p>";

# c:/apache/htdocs/aa_jakub/misc/alerts/util.php3, row 24
$_m["daily"]
  = "dennì";

# c:/apache/htdocs/aa_jakub/misc/alerts/util.php3, row 25
$_m["weekly"]
  = "týdnì";

# c:/apache/htdocs/aa_jakub/misc/alerts/util.php3, row 26
$_m["monthly"]
  = "mìsíènì";

# c:/apache/htdocs/aa_jakub/misc/alerts/util.php3, row 91
$_m["ERROR adding user to alerts_user"]
  = "CHYBA pøi pøidávání uživatele do alerts_user";

# c:/apache/htdocs/aa_jakub/misc/alerts/util.php3, row 96
$_m["ERROR updating user in alerts_user"]
  = "CHYBA pøi zmìnì nastavení v alerts_user";

# c:/apache/htdocs/aa_jakub/misc/alerts/util.php3, row 99
$_m["Welcome to APC e-mail alerts"]
  = "Vítejte v Zasílání zpráv";

# c:/apache/htdocs/aa_jakub/misc/alerts/util.php3, row 107
$_m["<p>Hello,</p><p>please confirm your subscription by clicking on URL:</p>%1<p>or copy the URL to your web browser so that we can see you did not subscribe by mistake and your e-mail is working.</p><p>Yours<br>&nbsp; &nbsp; &nbsp;APC Alerts moderators</p>"]
  = "<p>Dobrý den,</p><p>prosím potvrïte svou pøihlášku klepnutím na URL: </p>%1<p> nebo zkopírujte URL do Vašeho webového prohlížeèe, abychom poznali, že nejste zapsán(a) omylem a že Váš e-mail funguje.</p><p>Vaši<br>&nbsp; &nbsp; &nbsp;moderátoøi Zasílání zpráv</p>";

# c:/apache/htdocs/aa_jakub/misc/alerts/util.php3, row 150
$_m["Create new collection"]
  = "Vytvoøit novou kolekci";

# c:/apache/htdocs/aa_jakub/misc/alerts/util.php3, row 151
$_m["New collection"]
  = "Nová kolekce";

# c:/apache/htdocs/aa_jakub/misc/alerts/util.php3, row 153
$_m["Create"]
  = "Vytvoøit";

# c:/apache/htdocs/aa_jakub/misc/alerts/util.php3, row 180
$_m["Choose a filter"]
  = "Vyberte si filtr";

# c:/apache/htdocs/aa_jakub/misc/alerts/util.php3, row 210
$_m["Remove filters by setting order to 0."]
  = "Filtr odstraníte nastavením poøadí na 0.";

# c:/apache/htdocs/aa_jakub/misc/alerts/util.php3, row 214
$_m["Update"]
  = "Zmìnit";

# c:/apache/htdocs/aa_jakub/misc/alerts/util.php3, row 215
$_m["Delete"]
  = "Odstranit";

# c:/apache/htdocs/aa_jakub/misc/alerts/util.php3, row 219
$_m["Collection"]
  = "Kolekce";

# c:/apache/htdocs/aa_jakub/misc/alerts/util.php3, row 234
$_m["Order"]
  = "Poøadí";

# c:/apache/htdocs/aa_jakub/misc/alerts/util.php3, row 239
$_m["Add filter"]
  = "Pøidat filtr";

?>
