<?php
# $Id$
# Language: ES
# This file was automatically created by the Mini GetText environment
# on 25.9.2002 12:57

# Do not change this file otherwise than by typing translations on the right of =

# Before each message the places where it was used are noted.
# Look there if you are not sure how to translate it.

$mgettext_lang = "es";

# Unused messages
# End of unused messages

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/menu.php3, row 191
$_m["Wizard"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/menu.php3, row 192
$_m["Welcomes"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/menu.php3, row 193
$_m["Templates"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/menu.php3, row 195
$_m["Misc"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/menu.php3, row 196
# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 461, 462
$_m["Cron"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 371
$_m["Nothing to be shown."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 433
$_m["Quick Search: "]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 447, 451
$_m["Go"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 448
$_m["Complex Search (SQL WHERE clause): "]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 557
$_m["edit"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 561
$_m["delete"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 565
$_m["update"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 566
$_m["insert"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 832
$_m["Wrong value: a number between %1 and %2 is expected."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 849
$_m["This field is required."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 854
$_m["Not a valid integer number."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 858
$_m["Not a valid file name."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 862
$_m["Not a valid email address."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 875
$_m["Are you sure you want to permanently DELETE this record?"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 118
$_m["mail body"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 120
$_m["From: mail header"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 171, 172
$_m["Alerts Collection"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 177, 318
$_m["description"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 181, 321
$_m["standard"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 186, 324
$_m["no"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 186, 324
$_m["yes"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 188
$_m["mail header"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 195
$_m["Filters"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 199
$_m["Users"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 205
$_m["You don't have permissions to edit any collection or no collection exists."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 237
$_m["Error inserting Filter. Perhaps it is already in the collection."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 240
$_m["filter"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 249
$_m["order"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 277
$_m["There are no users subscribed to this collection yet."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 280, 361, 390
$_m["email"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 288, 441
$_m["how often"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 313
$_m["No collection uses any filter defined in any slice you have Admin permissions to."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 351
$_m["To add users use the standard Alerts User Interface."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 355, 356
$_m["Alerts Users"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 365, 393
$_m["first name"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 366, 394
$_m["last name"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 367, 395
$_m["language"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 371
$_m["No user is subscribed to any collection you have permissions to."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 384, 385
$_m["Alerts User"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 399
$_m["Collections"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 456
$_m["For help see FAQ: "]
  = "";

?>
