<?php
# $Id$
# Language: JA
# This file was automatically created by the Mini GetText environment
# on 8.10.2002 11:25

# Do not change this file otherwise than by typing translations on the right of =

# Before each message the places where it was used are noted.
# Look there if you are not sure how to translate it.

$mgettext_lang = "ja";

# Unused messages
# End of unused messages

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/add_user_collection.php3, row 46
$_m["Error - user was not subscribed"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/add_user_collection.php3, row 53
$_m["Missing required info"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/add_user_collection.php3, row 67
$_m["Howoften set wrong"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/add_user_collection.php3, row 75
$_m["Wrong collection ID"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/add_user_collection.php3, row 102
$_m["You have been successfully subscribed to AA Alerts for %1."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/add_user_collection.php3, row 110
$_m["You must first confirm your subscription (see confirmation e-mail) or subscribe again on %1 in order to receive e-mail Alerts."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/add_user_collection.php3, row 113
# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/alerts.php3, row 210
$_m["You can change your subscriptions on %1."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/alerts.php3, row 181
$_m["AA Alerts - daily digest of "]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/alerts.php3, row 182
$_m["AA Alerts - weekly digest of "]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/alerts.php3, row 183
$_m["AA Alerts - monthly digest of "]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/confirm.php3, row 38
$_m["Congratulations. Your subscription is finished."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/confirm.php3, row 42
$_m["Your code is not valid any more. Please subscribe again."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/confirm.php3, row 48
$_m["Subscribe to E-mail Alerts"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/confirm.php3, row 53
$_m["Finish your subscription to AA Alerts"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/confirm.php3, row 56
$_m["The code given is not OK. Please try it again. Don't use any spaces."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/confirm.php3, row 60
# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/subscribe.php3, row 58
$_m["Submit"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/index.php3, row 37, 48
$_m["This email is not registered with Alerts."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/index.php3, row 41
$_m["OK. Confirmation email was sent."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/index.php3, row 51
$_m["You have not yet confirmed your subscription. See confirmation e-mail or use Send confirmation."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/index.php3, row 60
$_m["Wrong password."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/index.php3, row 65
$_m["Login to Alerts sending"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/index.php3, row 71
$_m["Login to Personal settings for Alerts sending"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/index.php3, row 82
$_m["New user? Subscribe!"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/index.php3, row 84
# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/subscribe.php3, row 53
$_m["E-mail"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/index.php3, row 86
# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/subscribe.php3, row 55
$_m["Password"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/index.php3, row 89
$_m["Login"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/index.php3, row 90
$_m["Login by your e-mail address. If you don't use password, leave that box empty. If you forgot your password, click here and we will send a new confirmation e-mail to you."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/index.php3, row 91
$_m["Send confirmation"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/user_filter.php3, row 39
$_m["Your session has expired. Please login again."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/user_filter.php3, row 66
$_m["Passwords differ. Please try again."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/user_filter.php3, row 115, 125
$_m["AA Alerts"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/user_filter.php3, row 131
$_m["Welcome, %1"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/user_filter.php3, row 137
$_m["Language"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/user_filter.php3, row 142
$_m["First name"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/user_filter.php3, row 144
$_m["Last name"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/user_filter.php3, row 147
$_m["Change"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/user_filter.php3, row 152
$_m["New password"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/user_filter.php3, row 154
$_m["Retype password"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/user_filter.php3, row 157
$_m["Change password"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/user_filter.php3, row 204
$_m["Subscribed Collections"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/user_filter.php3, row 231
# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 157, 227
$_m["Filter"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/user_filter.php3, row 232, 273, 304
# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 217
$_m["How often"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/user_filter.php3, row 235
# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 218
$_m["unsubscribe"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/user_filter.php3, row 265, 282
$_m["Add"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/user_filter.php3, row 272
$_m["Add predefined collection"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/user_filter.php3, row 303
$_m["Add predefined filter"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/user_filter.php3, row 326
$_m["Sign out"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/subscribe.php3, row 34
$_m["An email with subscription informations was sent to you."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/subscribe.php3, row 38, 44
$_m["Subscribe to AA Alerts"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/subscribe.php3, row 51
$_m["We will send an e-mail message to the address given. Follow the instructions in it to complete your subscription."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/admin_mails.php3, row 73
$_m["Please confirm your subscription"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/admin_mails.php3, row 83
$_m["<p>Hello,</p><p>you didn't yet confirm your subscription to AA Alerts. You can't receive any emails until you do so. \n"
   ."                Please click on URL:</p>%1<p>or copy the URL to your web browser. \n"
   ."             The confirmation is done in order that we can see you did not subscribe by mistake and your e-mail is working.</p><p>Yours<br>&nbsp; &nbsp; &nbsp;APC Alerts moderators</p>"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 24
$_m["daily"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 25
$_m["weekly"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 26
$_m["monthly"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 87
$_m["ERROR adding user to alerts_user"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 92
$_m["ERROR updating user in alerts_user"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 95
$_m["Welcome to APC e-mail alerts"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 103
$_m["<p>Hello,</p><p>please confirm your subscription by clicking on URL:</p>%1<p>or copy the URL to your web browser so that we can see you did not subscribe by mistake and your e-mail is working.</p><p>Yours<br>&nbsp; &nbsp; &nbsp;APC Alerts moderators</p>"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 146
$_m["Create new collection"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 147
$_m["New collection"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 149
$_m["Create"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 176
$_m["Choose a filter"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 206
$_m["Remove filters by setting order to 0."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 210
$_m["Update"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 211
$_m["Delete"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 215
$_m["Collection"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 230
$_m["Order"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 235
$_m["Add filter"]
  = "";

?>
