<?php
# $Id$
# Language: RO
# This file was automatically created by the Mini GetText environment
# on 8.10.2002 11:33

# Do not change this file otherwise than by typing translations on the right of =

# Before each message the places where it was used are noted.
# Look there if you are not sure how to translate it.

$mgettext_lang = "ro";

# Unused messages
# End of unused messages

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/menu.php3, row 140
$_m["Admin"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/menu.php3, row 192
$_m["Wizard"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/menu.php3, row 193
$_m["Welcomes"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/menu.php3, row 194
$_m["Templates"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/menu.php3, row 196
$_m["Misc"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/menu.php3, row 197
# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 469, 470
$_m["Cron"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 217
# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit1.php3, row 272
$_m["order ascending"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 218
# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit1.php3, row 273
$_m["order descending"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 321
# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit1.php3, row 378
$_m["Nothing to be shown."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 393
# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit1.php3, row 444
$_m["Quick Search: "]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 407, 411
# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit1.php3, row 458, 462
$_m["Go"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 408
# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit1.php3, row 459
$_m["Complex Search (SQL WHERE clause): "]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 532
# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit1.php3, row 578
$_m["edit"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 536
# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit1.php3, row 582
$_m["delete"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 540
# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit1.php3, row 586
$_m["update"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 541
# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit1.php3, row 587
$_m["insert"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 547
$_m["cancel"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 884
# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit1.php3, row 905
$_m["Wrong value: a number between %1 and %2 is expected."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 901
# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit1.php3, row 922
$_m["This field is required."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 906
# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit1.php3, row 927
$_m["Not a valid integer number."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 910
# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit1.php3, row 931
$_m["Not a valid file name."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 914
# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit1.php3, row 935
$_m["Not a valid email address."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 927
# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit1.php3, row 948
$_m["Are you sure you want to permanently DELETE this record?"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 56
$_m["mail body"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 58
$_m["From: mail header"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 110, 111
$_m["Alerts Collection"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 116, 263
$_m["description"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 120, 266
$_m["standard"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 125, 269, 605
$_m["no"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 125, 269, 605
$_m["yes"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 127
$_m["mail header"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 134
$_m["Filters"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 138
$_m["Users"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 144
$_m["You don't have permissions to edit any collection or no collection exists."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 180
$_m["Error inserting Filter. Perhaps it is already in the collection."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 183
$_m["filter"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 193
$_m["order"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 208
$_m["Not yet confirmed"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 222
$_m["There are no users subscribed to this collection yet."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 225, 306, 336
$_m["email"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 233, 387
$_m["how often"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 258
$_m["No collection uses any filter defined in any slice you have Admin permissions to."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 296
$_m["To add users use the standard Alerts User Interface."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 300, 301
$_m["Alerts Users"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 310, 339
$_m["first name"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 311, 340
$_m["last name"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 312
$_m["confirmed"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 313, 341
$_m["language"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 317
$_m["No user is subscribed to any collection you have permissions to."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 330, 331
$_m["Alerts User"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 345
$_m["Collections"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 401, 402
$_m["Alerts Admin"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 414
$_m["confirm mail"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 421
$_m["delete not confirmed"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 428
$_m["last confirm mail"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 435
$_m["last delete not confirmed"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 451
$_m["This table sets handling of not confirmed users. It's accessible only\n"
   ."            to superadmins.\n"
   ."            You can delete not confirmed users after a number of days and / or send them an email \n"
   ."            demanding them to do confirmation\n"
   ."            after a smaller number of days. To switch either of the actions off,\n"
   ."            set number of days to 0. The two last fields are for your information only.<br>\n"
   ."            <br>\n"
   ."            To run the script, you must have cron set up with a row running\n"
   ."            misc/alerts/admin_mails.php3.<br>\n"
   ."            For more information, see <a href='http://apc-aa.sourceforge.net/faq/#1389'>the FAQ</a>."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 464
$_m["For help see FAQ: "]
  = "";

?>
