<?php
# $Id$
# Language: SK
# This file was automatically created by the Mini GetText environment
# on 30.9.2002 17:18

# Do not change this file otherwise than by typing translations on the right of =

# Before each message the places where it was used are noted.
# Look there if you are not sure how to translate it.

$mgettext_lang = "sk";

# Unused messages
# End of unused messages

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/menu.php3, row 191
$_m["Wizard"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/menu.php3, row 192
$_m["Welcomes"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/menu.php3, row 193
$_m["Templates"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/menu.php3, row 195
$_m["Misc"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/menu.php3, row 196
# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 475, 476
$_m["Cron"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 268
$_m["order ascending"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 269
$_m["order descending"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 374
$_m["Nothing to be shown."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 440
$_m["Quick Search: "]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 454, 458
$_m["Go"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 455
$_m["Complex Search (SQL WHERE clause): "]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 574
$_m["edit"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 578
$_m["delete"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 582
$_m["update"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 583
$_m["insert"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 860
$_m["Wrong value: a number between %1 and %2 is expected."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 877
$_m["This field is required."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 882
$_m["Not a valid integer number."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 886
$_m["Not a valid file name."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 890
$_m["Not a valid email address."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 903
$_m["Are you sure you want to permanently DELETE this record?"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 125
$_m["mail body"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 127
$_m["From: mail header"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 178, 179
$_m["Alerts Collection"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 184, 331
$_m["description"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 188, 334
$_m["standard"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 193, 337, 620
$_m["no"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 193, 337, 620
$_m["yes"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 195
$_m["mail header"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 202
$_m["Filters"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 206
$_m["Users"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 212
$_m["You don't have permissions to edit any collection or no collection exists."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 248
$_m["Error inserting Filter. Perhaps it is already in the collection."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 251
$_m["filter"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 261
$_m["order"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 276
$_m["Not yet confirmed"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 290
$_m["There are no users subscribed to this collection yet."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 293, 374, 404
$_m["email"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 301, 455
$_m["how often"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 326
$_m["No collection uses any filter defined in any slice you have Admin permissions to."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 364
$_m["To add users use the standard Alerts User Interface."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 368, 369
$_m["Alerts Users"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 378, 407
$_m["first name"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 379, 408
$_m["last name"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 380
$_m["confirmed"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 381, 409
$_m["language"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 385
$_m["No user is subscribed to any collection you have permissions to."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 398, 399
$_m["Alerts User"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 413
$_m["Collections"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 470
$_m["For help see FAQ: "]
  = "";

?>
