<?php
# $Id$
# Language: CZ
# This file was automatically created by the Mini GetText environment
# on 25.9.2002 12:49

# Do not change this file otherwise than by typing translations on the right of =

# Before each message the places where it was used are noted.
# Look there if you are not sure how to translate it.

$mgettext_lang = "cz";

# Unused messages
$_m["Alerts - Collections"]
  = "Zasílání zpráv - Kolekce";
$_m["First create some view of type Alerts Digest and define some filters there."]
  = "Nejprve vytvoøte nìjaký pohled typu Zasílání zpráv a nadefinujte tam nìjaké filtry.";
$_m["Cancel"]
  = "Zrušit";
$_m["Alerts Collections - Email Headers"]
  = "Zasílání Zpráv - Hlavièky Emailù pro Kolekce";
# End of unused messages

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/alerts.php3, row 177
$_m["AA Alerts - daily digest of "]
  = "Zasílání zpráv - denní souhrn ";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/alerts.php3, row 178
$_m["AA Alerts - weekly digest of "]
  = "Zasílání zpráv - týdenní souhrn ";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/alerts.php3, row 179
$_m["AA Alerts - monthly digest of "]
  = "Zasílání zpráv - mìsíèní souhrn ";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/alerts.php3, row 203
# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/add_user_collection.php3, row 110
$_m["You can change your subscriptions on %1."]
  = "Své objednávky mùžete zmìnit na %1.";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/confirm.php3, row 38
$_m["Congratulations. Your subscription is finished."]
  = "Blahopøejeme. Dokonèil(a) jste své pøihlášení.";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/confirm.php3, row 43
$_m["Subscribe to E-mail Alerts"]
  = "Pøihlašte se k Zasílání zpráv";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/confirm.php3, row 47
$_m["Finish your subscription to AA Alerts"]
  = "Dokonèete pøihlašování k Zasílání zpráv";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/confirm.php3, row 50
$_m["The code given is not OK. Please try it again. Don't use any spaces."]
  = "Zadaný kód není správný. Prosím zkuste ho zadat znovu. Nepište mezery.";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/confirm.php3, row 55
# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/subscribe.php3, row 56
$_m["Submit"]
  = "Odeslat";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/index.php3, row 36, 47
$_m["This email is not registered with Alerts."]
  = "Tento email není pøihlášen k Zasílání zpráv.";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/index.php3, row 40
$_m["OK. Password was sent."]
  = "OK. Heslo je posláno.";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/index.php3, row 58
$_m["Wrong password."]
  = "Špatné heslo";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/index.php3, row 63
$_m["Login to Alerts sending"]
  = "Pøihlašte se k Zasílání zpráv";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/index.php3, row 68
$_m["Login to Personal settings for Alerts sending"]
  = "Pøihlašte se k osobnímu nastavení Zasílání zpráv";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/index.php3, row 78
$_m["New user? Subscribe!"]
  = "Nový uživatel? Pøihlašte se!";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/index.php3, row 80
# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/subscribe.php3, row 51
$_m["E-mail"]
  = "E-mail";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/index.php3, row 82
# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/subscribe.php3, row 53
$_m["Password"]
  = "Heslo";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/index.php3, row 85
$_m["Login"]
  = "Vstoupit";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/index.php3, row 86
$_m["Login by your e-mail address. If you don't use password, leave that box empty. If you forgot your password, click here and we will send a new confirmation e-mail to you."]
  = "Pøihlašte se pomocí e-mailové adresy. Pokud nepoužíváte heslo, nechte jeho okénko prázdné. Pokud jste heslo zapomnìli, klepnìte zde a my vám pošleme nový potvrzovací e-mail.";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/index.php3, row 86
$_m["Send password"]
  = "Poslat heslo";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/user_filter.php3, row 39
$_m["Your session has expired. Please login again."]
  = "Vaše relace vypršela. Pøihlaste se prosím znovu.";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/user_filter.php3, row 65
$_m["Passwords differ. Please try again."]
  = "Hesla se liší. Zkuste to prosím znovu.";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/user_filter.php3, row 107, 119
$_m["AA Alerts"]
  = "Zasílání zpráv";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/user_filter.php3, row 125
$_m["Welcome, %1"]
  = "Dobrý den! Uživatel: %1";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/user_filter.php3, row 131
$_m["First name"]
  = "Køestní jméno";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/user_filter.php3, row 133
$_m["Last name"]
  = "Pøíjmení";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/user_filter.php3, row 136
$_m["Change"]
  = "Zmìnit";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/user_filter.php3, row 141
$_m["New password"]
  = "Nové heslo";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/user_filter.php3, row 143
$_m["Retype password"]
  = "Potvrïte heslo";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/user_filter.php3, row 146
$_m["Change password"]
  = "Zmìnit heslo";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/user_filter.php3, row 192
$_m["Subscribed Collections"]
  = "Objednané Kolekce";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/user_filter.php3, row 217
# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 156, 226
$_m["Filter"]
  = "Filtr";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/user_filter.php3, row 218, 256, 285
# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 216
$_m["How often"]
  = "Jak èasto";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/user_filter.php3, row 221
# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 217
$_m["unsubscribe"]
  = "zrušit odbìr";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/user_filter.php3, row 248, 265
$_m["Add"]
  = "Pøidat";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/user_filter.php3, row 255
$_m["Add predefined collection"]
  = "Pøidejte pøeddefinovanou kolekci";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/user_filter.php3, row 284
$_m["Add predefined filter"]
  = "Pøidat pøeddefinovaný filtr";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/user_filter.php3, row 305
$_m["Sign out"]
  = "Odhlásit se";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/subscribe.php3, row 33
$_m["An email with subscription informations was sent to you."]
  = "Email s pøihlašovacími informacemi vám byl zaslán.";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/subscribe.php3, row 37, 42
$_m["Subscribe to AA Alerts"]
  = "Pøihlašte se k Zasílání zpráv";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/subscribe.php3, row 49
$_m["We will send an e-mail message to the address given. Follow the instructions in it to complete your subscription."]
  = "Na zadanou adresu pošleme e-mail. Následujte instrukce v nìm obsažené k dokonèení pøihlášení.";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 24
$_m["daily"]
  = "dennì";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 25
$_m["weekly"]
  = "týdnì";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 26
$_m["monthly"]
  = "mìsíènì";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 84
$_m["ERROR adding user to alerts_user"]
  = "CHYBA pøi pøidávání uživatele do alerts_user";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 89
$_m["ERROR updating user in alerts_user"]
  = "CHYBA pøi zmìnì nastavení v alerts_user";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 92
$_m["Welcome to APC e-mail alerts"]
  = "Vítejte v Zasílání zpráv";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 102
$_m["<p>Hello,</p><p>please confirm your subscription on</p>%1<p>Write the code</p>%2<p>into the box so that we can see you did not subscribe by mistake and your e-mail is working.</p><p>Yours<br>&nbsp; &nbsp; &nbsp;APC Alerts moderators</p>"]
  = "<p>Dobrý den,</p><p>prosím potvrïte svou pøihlášku na </p>%1<p>Napište kód</p>%2<p>do okénka, abychom poznali, že nejste zapsán(a) omylem a že Váš e-mail funguje.</p><p>Vaši<br>&nbsp; &nbsp; &nbsp;moderátoøi Zasílání zpráv</p>";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 145
$_m["Create new collection"]
  = "Vytvoøit novou kolekci";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 146
$_m["New collection"]
  = "Nová kolekce";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 148
$_m["Create"]
  = "Vytvoøit";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 175
$_m["Choose a filter"]
  = "Vyberte si filtr";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 205
$_m["Remove filters by setting order to 0."]
  = "Filtr odstraníte nastavením poøadí na 0.";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 209
$_m["Update"]
  = "Zmìnit";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 210
$_m["Delete"]
  = "Odstranit";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 214
$_m["Collection"]
  = "Kolekce";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 229
$_m["Order"]
  = "Poøadí";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 234
$_m["Add filter"]
  = "Pøidat filtr";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/add_user_collection.php3, row 45
$_m["Error - user was not subscribed"]
  = "Chyba - uživatel nebyl zapsán";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/add_user_collection.php3, row 51
$_m["Missing required info"]
  = "Chybí požadovaný údaj";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/add_user_collection.php3, row 65
$_m["Howoften set wrong"]
  = "\"Jak èasto\" je nastaveno špatnì";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/add_user_collection.php3, row 73
$_m["Wrong collection ID"]
  = "Špatné ID kolekce";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/add_user_collection.php3, row 99
$_m["You have been successfully subscribed to AA Alerts for %1."]
  = "Byl(a) jste úspìšnì zapsán(a) do Zasílání zpráv pro %1.";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/add_user_collection.php3, row 107
$_m["You must first confirm your subscription (see confirmation e-mail) or subscribe again on %1 in order to receive e-mail Alerts."]
  = "Nejdøíve musíte potvrdit své pøihlášení (viz potvrzovací e-mail) nebo se znovu pøihlásit na %1, abyste mohl(a) dostávat zprávy.";

?>
