<?php
# $Id$
# Language: CZ
# This file was automatically created by the Mini GetText environment
# on 18.9.2002 17:31

# Do not change this file otherwise than by typing translations on the right of =

# Before each message the places where it was used are noted.
# Look there if you are not sure how to translate it.

$mgettext_lang = "cz";

# Unused messages
# End of unused messages

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/menu.php3, row 190
$_m["Wizard"]
  = "Prùvodce";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/menu.php3, row 191
$_m["Welcomes"]
  = "Vítací maily";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/menu.php3, row 192
$_m["Templates"]
  = "Šablony";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/menu.php3, row 194
$_m["Misc"]
  = "Rùzné";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/menu.php3, row 195
# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 420, 421
$_m["Cron"]
  = "Cron";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 295
$_m["Nothing to be shown."]
  = "Není co zobrazit";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 349
$_m["Quick Search: "]
  = "Rychlé Hledání: ";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 363, 367
$_m["Go"]
  = "Jeï";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 364
$_m["Complex Search (SQL WHERE clause): "]
  = "Komplexní hledání (pøíkaz SQL WHERE): ";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 739
$_m["Wrong value: a number between %1 and %2 is expected."]
  = "Špatná hodnota: oèekává se èíslo mezi %1 a %2.";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 756
$_m["This field is required."]
  = "Toto pole je povinné.";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 761
$_m["Not a valid integer number."]
  = "Není platné celé èíslo.";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 765
$_m["Not a valid file name."]
  = "Není platný název souboru.";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 769
$_m["Not a valid email address."]
  = "Není platný email.";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 782
$_m["Are you sure you want to permanently DELETE this record?"]
  = "Chcete opravdu trvale SMAZAT tento záznam?";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 103
$_m["mail body"]
  = "tìlo zprávy";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 105
$_m["From: mail header"]
  = "From: hlavièka mailu";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 156, 157
$_m["Alerts Collection"]
  = "Zasílání Zpráv - Kolekce";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 174
$_m["Filters"]
  = "Filtry";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 178
$_m["Users"]
  = "Uživatelé";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 183
$_m["You don't have permissions to edit any collection or no collection exists."]
  = "Nemáte práva na editování žádné kolekce nebo žádná kolekce neexistuje.";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 226
$_m["order"]
  = "poøadí";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 249
$_m["There are no users subscribed to this collection yet."]
  = "Žádní uživatelé nejsou ještì zapsaní k této kolekci.";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 280
$_m["No collection uses any filter defined in any slice you have Admin permissions to."]
  = "Žádná kolekce nepoužívá filtr z žádného webíku, ke kterému máte Admin práva.";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 291
$_m["0 = special or user def"]
  = "0 = speciální nebo uživatelská";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 315
$_m["To add users use the standard Alerts User Interface."]
  = "Pro pøidání uživatele použijte standardní Uživatelské Rozhraní pro Zasílání zpráv.";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 319, 320
$_m["Alerts Users"]
  = "Zasílání Zpráv - Uživatelé";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 333
$_m["No user is subscribed to any collection you have permissions to."]
  = "Žádný uživatel není zapsán k žádné kolekci, ke které máte práva.";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 346, 347
$_m["Alerts User"]
  = "Zasílání Zpráv - Uživatel";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 360
$_m["Collections"]
  = "Kolekce";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 415
$_m["For help see FAQ: "]
  = "Nápovìdu najdete ve FAQu: ";

?>
