<?php
# $Id$
# Language: CZ
# This file was automatically created by the Mini GetText environment
# on 8.10.2002 11:33

# Do not change this file otherwise than by typing translations on the right of =

# Before each message the places where it was used are noted.
# Look there if you are not sure how to translate it.

$mgettext_lang = "cz";

# Unused messages
$_m["0 = special or user def"]
  = "0 = speciální nebo uživatelská";
# End of unused messages

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/menu.php3, row 140
$_m["Admin"]
  = "Administrace";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/menu.php3, row 192
$_m["Wizard"]
  = "Prùvodce";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/menu.php3, row 193
$_m["Welcomes"]
  = "Vítací maily";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/menu.php3, row 194
$_m["Templates"]
  = "Šablony";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/menu.php3, row 196
$_m["Misc"]
  = "Rùzné";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/menu.php3, row 197
# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 469, 470
$_m["Cron"]
  = "Cron";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 217
# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit1.php3, row 272
$_m["order ascending"]
  = "seøadit vzestupnì";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 218
# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit1.php3, row 273
$_m["order descending"]
  = "seøadit sestupnì";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 321
# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit1.php3, row 378
$_m["Nothing to be shown."]
  = "Není co zobrazit";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 393
# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit1.php3, row 444
$_m["Quick Search: "]
  = "Rychlé Hledání: ";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 407, 411
# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit1.php3, row 458, 462
$_m["Go"]
  = "Jeï";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 408
# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit1.php3, row 459
$_m["Complex Search (SQL WHERE clause): "]
  = "Komplexní hledání (pøíkaz SQL WHERE): ";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 532
# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit1.php3, row 578
$_m["edit"]
  = "upravit";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 536
# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit1.php3, row 582
$_m["delete"]
  = "smazat";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 540
# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit1.php3, row 586
$_m["update"]
  = "odeslat";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 541
# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit1.php3, row 587
$_m["insert"]
  = "vložit";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 547
$_m["cancel"]
  = "storno";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 884
# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit1.php3, row 905
$_m["Wrong value: a number between %1 and %2 is expected."]
  = "Špatná hodnota: oèekává se èíslo mezi %1 a %2.";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 901
# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit1.php3, row 922
$_m["This field is required."]
  = "Toto pole je povinné.";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 906
# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit1.php3, row 927
$_m["Not a valid integer number."]
  = "Není platné celé èíslo.";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 910
# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit1.php3, row 931
$_m["Not a valid file name."]
  = "Není platný název souboru.";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 914
# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit1.php3, row 935
$_m["Not a valid email address."]
  = "Není platný email.";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 927
# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit1.php3, row 948
$_m["Are you sure you want to permanently DELETE this record?"]
  = "Chcete opravdu trvale SMAZAT tento záznam?";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 56
$_m["mail body"]
  = "tìlo zprávy";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 58
$_m["From: mail header"]
  = "From: hlavièka mailu";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 110, 111
$_m["Alerts Collection"]
  = "Zasílání Zpráv - Kolekce";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 116, 263
$_m["description"]
  = "popis";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 120, 266
$_m["standard"]
  = "standartní";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 125, 269, 605
$_m["no"]
  = "ne";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 125, 269, 605
$_m["yes"]
  = "ano";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 127
$_m["mail header"]
  = "hlavièka mailu";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 134
$_m["Filters"]
  = "Filtry";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 138
$_m["Users"]
  = "Uživatelé";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 144
$_m["You don't have permissions to edit any collection or no collection exists."]
  = "Nemáte práva na editování žádné kolekce nebo žádná kolekce neexistuje.";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 180
$_m["Error inserting Filter. Perhaps it is already in the collection."]
  = "Chyba pøi vkládání Filtru. Pravdìpodobnì už je v kolekci.";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 183
$_m["filter"]
  = "filtr";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 193
$_m["order"]
  = "poøadí";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 208
$_m["Not yet confirmed"]
  = "Dosud nepotvrzen(a)";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 222
$_m["There are no users subscribed to this collection yet."]
  = "Žádní uživatelé nejsou ještì zapsaní k této kolekci.";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 225, 306, 336
$_m["email"]
  = "email";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 233, 387
$_m["how often"]
  = "jak èasto";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 258
$_m["No collection uses any filter defined in any slice you have Admin permissions to."]
  = "Žádná kolekce nepoužívá filtr z žádného webíku, ke kterému máte Admin práva.";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 296
$_m["To add users use the standard Alerts User Interface."]
  = "Pro pøidání uživatele použijte standardní Uživatelské Rozhraní pro Zasílání zpráv.";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 300, 301
$_m["Alerts Users"]
  = "Zasílání Zpráv - Uživatelé";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 310, 339
$_m["first name"]
  = "køestní jméno";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 311, 340
$_m["last name"]
  = "pøíjmení";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 312
$_m["confirmed"]
  = "potvrzen(a)";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 313, 341
$_m["language"]
  = "jazyk";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 317
$_m["No user is subscribed to any collection you have permissions to."]
  = "Žádný uživatel není zapsán k žádné kolekci, ke které máte práva.";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 330, 331
$_m["Alerts User"]
  = "Zasílání Zpráv - Uživatel";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 345
$_m["Collections"]
  = "Kolekce";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 401, 402
$_m["Alerts Admin"]
  = "Administrace Zasílání Zpráv";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 414
$_m["confirm mail"]
  = "potvrzovací mail";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 421
$_m["delete not confirmed"]
  = "smazat nepotvrzené";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 428
$_m["last confirm mail"]
  = "minulý potvrzovací mail";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 435
$_m["last delete not confirmed"]
  = "minulé smazat nepotvrzené";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 451
$_m["This table sets handling of not confirmed users. It's accessible only\n"
   ."            to superadmins.\n"
   ."            You can delete not confirmed users after a number of days and / or send them an email \n"
   ."            demanding them to do confirmation\n"
   ."            after a smaller number of days. To switch either of the actions off,\n"
   ."            set number of days to 0. The two last fields are for your information only.<br>\n"
   ."            <br>\n"
   ."            To run the script, you must have cron set up with a row running\n"
   ."            misc/alerts/admin_mails.php3.<br>\n"
   ."            For more information, see <a href='http://apc-aa.sourceforge.net/faq/#1389'>the FAQ</a>."]
  = "Tato tabulka nastavuje zacházení s nepotvrzenými uživateli. Je pøístupná pouze superadminùm.\n"
   ."            Mùžete mazat nepotvrzené uživatele po urèitém poètu dní a / nebo jim poslat email žádající, aby provedli potvrzení\n"
   ."            po menším poètu dní. Pro vypnutí nìkteré z akcí nastavte poèet dní na 0. Poslední dvì pole jsou jen pro Vaši informaci.<br>\n"
   ."            <br>\n"
   ."            Pro spuštìní skriptu musíte mít cron nastavený s øádkou spouštìjící\n"
   ."            misc/alerts/admin_mails.php3.<br>\n"
   ."            Více viz <a href='http://apc-aa.sourceforge.net/faq/#1389'>FAQ</a>.";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 464
$_m["For help see FAQ: "]
  = "Nápovìdu najdete ve FAQu: ";

?>
