<?php
# $Id$
# Language: EN
# This file was automatically created by the Mini GetText environment
# on 18.9.2002 17:31

# Do not change this file otherwise than by typing translations on the right of =

# Before each message the places where it was used are noted.
# Look there if you are not sure how to translate it.

$mgettext_lang = "en";

# Unused messages
# End of unused messages

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/menu.php3, row 190
$_m["Wizard"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/menu.php3, row 191
$_m["Welcomes"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/menu.php3, row 192
$_m["Templates"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/menu.php3, row 194
$_m["Misc"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/menu.php3, row 195
# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 420, 421
$_m["Cron"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 295
$_m["Nothing to be shown."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 349
$_m["Quick Search: "]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 363, 367
$_m["Go"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 364
$_m["Complex Search (SQL WHERE clause): "]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 739
$_m["Wrong value: a number between %1 and %2 is expected."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 756
$_m["This field is required."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 761
$_m["Not a valid integer number."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 765
$_m["Not a valid file name."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 769
$_m["Not a valid email address."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tabledit.php3, row 782
$_m["Are you sure you want to permanently DELETE this record?"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 103
$_m["mail body"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 105
$_m["From: mail header"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 156, 157
$_m["Alerts Collection"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 174
$_m["Filters"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 178
$_m["Users"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 183
$_m["You don't have permissions to edit any collection or no collection exists."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 226
$_m["order"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 249
$_m["There are no users subscribed to this collection yet."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 280
$_m["No collection uses any filter defined in any slice you have Admin permissions to."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 291
$_m["0 = special or user def"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 315
$_m["To add users use the standard Alerts User Interface."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 319, 320
$_m["Alerts Users"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 333
$_m["No user is subscribed to any collection you have permissions to."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 346, 347
$_m["Alerts User"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 360
$_m["Collections"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/include/tableviews.php3, row 415
$_m["For help see FAQ: "]
  = "";

?>
