<?php
# $Id$
# Language: EN
# This file was automatically created by the Mini GetText environment
# on 11.10.2002 17:37

# Do not change this file otherwise than by typing translations on the right of =

# Before each message the places where it was used are noted.
# Look there if you are not sure how to translate it.

$mgettext_lang = "en";

# Unused messages
# End of unused messages

# c:/apache/htdocs/aa_jakub/include/menu.php3, row 140
$_m["Admin"]
  = "";

# c:/apache/htdocs/aa_jakub/include/menu.php3, row 192
$_m["Wizard"]
  = "";

# c:/apache/htdocs/aa_jakub/include/menu.php3, row 193
$_m["Welcomes"]
  = "";

# c:/apache/htdocs/aa_jakub/include/menu.php3, row 194
$_m["Templates"]
  = "";

# c:/apache/htdocs/aa_jakub/include/menu.php3, row 196
$_m["Misc"]
  = "";

# c:/apache/htdocs/aa_jakub/include/menu.php3, row 197
# c:/apache/htdocs/aa_jakub/include/tableviews.php3, row 463, 464
$_m["Cron"]
  = "";

# c:/apache/htdocs/aa_jakub/include/tabledit.php3, row 296
# c:/apache/htdocs/aa_jakub/include/tabledit1.php3, row 272
$_m["order ascending"]
  = "";

# c:/apache/htdocs/aa_jakub/include/tabledit.php3, row 297
# c:/apache/htdocs/aa_jakub/include/tabledit1.php3, row 273
$_m["order descending"]
  = "";

# c:/apache/htdocs/aa_jakub/include/tabledit.php3, row 334
# c:/apache/htdocs/aa_jakub/include/tabledit1.php3, row 378
$_m["Nothing to be shown."]
  = "";

# c:/apache/htdocs/aa_jakub/include/tabledit.php3, row 406
# c:/apache/htdocs/aa_jakub/include/tabledit1.php3, row 444
$_m["Quick Search: "]
  = "";

# c:/apache/htdocs/aa_jakub/include/tabledit.php3, row 416, 420
# c:/apache/htdocs/aa_jakub/include/tabledit1.php3, row 458, 462
$_m["Go"]
  = "";

# c:/apache/htdocs/aa_jakub/include/tabledit.php3, row 417
# c:/apache/htdocs/aa_jakub/include/tabledit1.php3, row 459
$_m["Complex Search (SQL WHERE clause): "]
  = "";

# c:/apache/htdocs/aa_jakub/include/tabledit.php3, row 609
# c:/apache/htdocs/aa_jakub/include/tabledit1.php3, row 578
$_m["edit"]
  = "";

# c:/apache/htdocs/aa_jakub/include/tabledit.php3, row 614
$_m["add"]
  = "";

# c:/apache/htdocs/aa_jakub/include/tabledit.php3, row 619, 626
# c:/apache/htdocs/aa_jakub/include/tabledit1.php3, row 582
$_m["delete"]
  = "";

# c:/apache/htdocs/aa_jakub/include/tabledit.php3, row 626, 637
# c:/apache/htdocs/aa_jakub/include/tabledit1.php3, row 587
$_m["insert"]
  = "";

# c:/apache/htdocs/aa_jakub/include/tabledit.php3, row 632
$_m["delete checked"]
  = "";

# c:/apache/htdocs/aa_jakub/include/tabledit.php3, row 637
# c:/apache/htdocs/aa_jakub/include/tabledit1.php3, row 586
$_m["update"]
  = "";

# c:/apache/htdocs/aa_jakub/include/tabledit.php3, row 642
$_m["update all"]
  = "";

# c:/apache/htdocs/aa_jakub/include/tabledit.php3, row 647
$_m["cancel"]
  = "";

# c:/apache/htdocs/aa_jakub/include/tabledit.php3, row 684
$_m["Are you sure you want to permanently DELETE all the checked records?"]
  = "";

# c:/apache/htdocs/aa_jakub/include/tabledit.php3, row 1054
# c:/apache/htdocs/aa_jakub/include/tabledit1.php3, row 905
$_m["Wrong value: a number between %1 and %2 is expected."]
  = "";

# c:/apache/htdocs/aa_jakub/include/tabledit.php3, row 1071
# c:/apache/htdocs/aa_jakub/include/tabledit1.php3, row 922
$_m["This field is required."]
  = "";

# c:/apache/htdocs/aa_jakub/include/tabledit.php3, row 1076
# c:/apache/htdocs/aa_jakub/include/tabledit1.php3, row 927
$_m["Not a valid integer number."]
  = "";

# c:/apache/htdocs/aa_jakub/include/tabledit.php3, row 1080
# c:/apache/htdocs/aa_jakub/include/tabledit1.php3, row 931
$_m["Not a valid file name."]
  = "";

# c:/apache/htdocs/aa_jakub/include/tabledit.php3, row 1084
# c:/apache/htdocs/aa_jakub/include/tabledit1.php3, row 935
$_m["Not a valid email address."]
  = "";

# c:/apache/htdocs/aa_jakub/include/tabledit.php3, row 1097
# c:/apache/htdocs/aa_jakub/include/tabledit1.php3, row 948
$_m["Are you sure you want to permanently DELETE this record?"]
  = "";

# c:/apache/htdocs/aa_jakub/include/tableviews.php3, row 56
$_m["mail body"]
  = "";

# c:/apache/htdocs/aa_jakub/include/tableviews.php3, row 58
$_m["From: mail header"]
  = "";

# c:/apache/htdocs/aa_jakub/include/tableviews.php3, row 106, 107
$_m["Alerts Collection"]
  = "";

# c:/apache/htdocs/aa_jakub/include/tableviews.php3, row 112, 256
$_m["description"]
  = "";

# c:/apache/htdocs/aa_jakub/include/tableviews.php3, row 116, 259
$_m["standard"]
  = "";

# c:/apache/htdocs/aa_jakub/include/tableviews.php3, row 121, 262, 599
$_m["no"]
  = "";

# c:/apache/htdocs/aa_jakub/include/tableviews.php3, row 121, 262, 599
$_m["yes"]
  = "";

# c:/apache/htdocs/aa_jakub/include/tableviews.php3, row 123, 267
$_m["mail header"]
  = "";

# c:/apache/htdocs/aa_jakub/include/tableviews.php3, row 130
$_m["Filters"]
  = "";

# c:/apache/htdocs/aa_jakub/include/tableviews.php3, row 134
$_m["Users"]
  = "";

# c:/apache/htdocs/aa_jakub/include/tableviews.php3, row 140
$_m["You don't have permissions to edit any collection or no collection exists."]
  = "";

# c:/apache/htdocs/aa_jakub/include/tableviews.php3, row 176
$_m["Error inserting Filter. Perhaps it is already in the collection."]
  = "";

# c:/apache/htdocs/aa_jakub/include/tableviews.php3, row 179
$_m["filter"]
  = "";

# c:/apache/htdocs/aa_jakub/include/tableviews.php3, row 189
$_m["order"]
  = "";

# c:/apache/htdocs/aa_jakub/include/tableviews.php3, row 204
$_m["Not yet confirmed"]
  = "";

# c:/apache/htdocs/aa_jakub/include/tableviews.php3, row 217
$_m["There are no users subscribed to this collection yet."]
  = "";

# c:/apache/htdocs/aa_jakub/include/tableviews.php3, row 220, 301, 331
$_m["email"]
  = "";

# c:/apache/htdocs/aa_jakub/include/tableviews.php3, row 228, 382
$_m["how often"]
  = "";

# c:/apache/htdocs/aa_jakub/include/tableviews.php3, row 251
$_m["No collection uses any filter defined in any slice you have Admin permissions to."]
  = "";

# c:/apache/htdocs/aa_jakub/include/tableviews.php3, row 291
$_m["To add users use the standard Alerts User Interface."]
  = "";

# c:/apache/htdocs/aa_jakub/include/tableviews.php3, row 294, 295
$_m["Alerts Users"]
  = "";

# c:/apache/htdocs/aa_jakub/include/tableviews.php3, row 305, 334
$_m["first name"]
  = "";

# c:/apache/htdocs/aa_jakub/include/tableviews.php3, row 306, 335
$_m["last name"]
  = "";

# c:/apache/htdocs/aa_jakub/include/tableviews.php3, row 307
$_m["confirmed"]
  = "";

# c:/apache/htdocs/aa_jakub/include/tableviews.php3, row 308, 336
$_m["language"]
  = "";

# c:/apache/htdocs/aa_jakub/include/tableviews.php3, row 312
$_m["No user is subscribed to any collection you have permissions to."]
  = "";

# c:/apache/htdocs/aa_jakub/include/tableviews.php3, row 325, 326
$_m["Alerts User"]
  = "";

# c:/apache/htdocs/aa_jakub/include/tableviews.php3, row 340
$_m["Collections"]
  = "";

# c:/apache/htdocs/aa_jakub/include/tableviews.php3, row 396, 397
$_m["Alerts Admin"]
  = "";

# c:/apache/htdocs/aa_jakub/include/tableviews.php3, row 409
$_m["confirm mail"]
  = "";

# c:/apache/htdocs/aa_jakub/include/tableviews.php3, row 410, 417
$_m["number of days, 0 = off"]
  = "";

# c:/apache/htdocs/aa_jakub/include/tableviews.php3, row 416
$_m["delete not confirmed"]
  = "";

# c:/apache/htdocs/aa_jakub/include/tableviews.php3, row 423
$_m["last confirm mail"]
  = "";

# c:/apache/htdocs/aa_jakub/include/tableviews.php3, row 430
$_m["last delete not confirmed"]
  = "";

# c:/apache/htdocs/aa_jakub/include/tableviews.php3, row 446
$_m["This table sets handling of not confirmed users. It's accessible only\n"
   ."            to superadmins.\n"
   ."            You can delete not confirmed users after a number of days and / or send them an email \n"
   ."            demanding them to do confirmation\n"
   ."            after a smaller number of days. To switch either of the actions off,\n"
   ."            set number of days to 0. The two last fields are for your information only.<br>\n"
   ."            <br>\n"
   ."            To run the script, you must have cron set up with a row running\n"
   ."            misc/alerts/admin_mails.php3.<br>\n"
   ."            For more information, see <a href='http://apc-aa.sourceforge.net/faq/#1389'>the FAQ</a>."]
  = "";

# c:/apache/htdocs/aa_jakub/include/tableviews.php3, row 459
$_m["For help see FAQ: "]
  = "";

?>
