<?php
# $Id$
# Language: ES
# This file was automatically created by the Mini GetText environment
# on 28.8.2002 12:41

# Do not change this file otherwise than by typing translations on the right of =

# Before each message the places where it was used are noted.
# Look there if you are not sure how to translate it.

$mgettext_lang = "es";

# Unused messages
# End of unused messages

# misc/alerts/alerts.php3, row 37
$_m["AA Alerts - daily digest of "]
  = "";

# misc/alerts/alerts.php3, row 38
$_m["AA Alerts - weekly digest of "]
  = "";

# misc/alerts/alerts.php3, row 39
$_m["AA Alerts - monthly digest of "]
  = "";

# misc/alerts/alerts.php3, row 173
# misc/alerts/add_user_collection.php3, row 110
$_m["You can change your subscriptions on %1."]
  = "";

# misc/alerts/confirm.php3, row 38
$_m["Congratulations. Your subscription is finished."]
  = "";

# misc/alerts/confirm.php3, row 43
$_m["Subscribe to E-mail Alerts"]
  = "";

# misc/alerts/confirm.php3, row 47
$_m["Finish your subscription to AA Alerts"]
  = "";

# misc/alerts/confirm.php3, row 50
$_m["The code given is not OK. Please try it again. Don't use any spaces."]
  = "";

# misc/alerts/confirm.php3, row 55
# misc/alerts/subscribe.php3, row 56
$_m["Submit"]
  = "";

# misc/alerts/add_user_collection.php3, row 45
$_m["Error - user was not subscribed"]
  = "";

# misc/alerts/add_user_collection.php3, row 51
$_m["Missing required info"]
  = "";

# misc/alerts/add_user_collection.php3, row 65
$_m["Howoften set wrong"]
  = "";

# misc/alerts/add_user_collection.php3, row 73
$_m["Wrong collection ID"]
  = "";

# misc/alerts/add_user_collection.php3, row 99
$_m["You have been successfully subscribed to AA Alerts for %1."]
  = "";

# misc/alerts/add_user_collection.php3, row 107
$_m["You must first confirm your subscription (see confirmation e-mail) or subscribe again on %1 in order to receive e-mail Alerts."]
  = "";

# misc/alerts/index.php3, row 36, 47
$_m["This email is not registered with Alerts."]
  = "";

# misc/alerts/index.php3, row 40
$_m["OK. Password was sent."]
  = "";

# misc/alerts/index.php3, row 58
$_m["Wrong password."]
  = "";

# misc/alerts/index.php3, row 63
$_m["Login to Alerts sending"]
  = "";

# misc/alerts/index.php3, row 68
$_m["Login to Personal settings for Alerts sending"]
  = "";

# misc/alerts/index.php3, row 78
$_m["New user? Subscribe!"]
  = "";

# misc/alerts/index.php3, row 80
# misc/alerts/subscribe.php3, row 51
$_m["E-mail"]
  = "";

# misc/alerts/index.php3, row 82
# misc/alerts/subscribe.php3, row 53
$_m["Password"]
  = "";

# misc/alerts/index.php3, row 85
$_m["Login"]
  = "";

# misc/alerts/index.php3, row 86
$_m["Login by your e-mail address. If you don't use password, leave that box empty. If you forgot your password, click here and we will send a new confirmation e-mail to you."]
  = "";

# misc/alerts/index.php3, row 86
$_m["Send password"]
  = "";

# misc/alerts/subscribe.php3, row 33
$_m["An email with subscription informations was sent to you."]
  = "";

# misc/alerts/subscribe.php3, row 37, 42
$_m["Subscribe to AA Alerts"]
  = "";

# misc/alerts/subscribe.php3, row 49
$_m["We will send an e-mail message to the address given. Follow the instructions in it to complete your subscription."]
  = "";

# misc/alerts/user_filter.php3, row 39
$_m["Your session has expired. Please login again."]
  = "";

# misc/alerts/user_filter.php3, row 65
$_m["Passwords differ. Please try again."]
  = "";

# misc/alerts/user_filter.php3, row 107, 119
$_m["AA Alerts"]
  = "";

# misc/alerts/user_filter.php3, row 125
$_m["Welcome, %1"]
  = "";

# misc/alerts/user_filter.php3, row 131
$_m["First name"]
  = "";

# misc/alerts/user_filter.php3, row 133
$_m["Last name"]
  = "";

# misc/alerts/user_filter.php3, row 136
$_m["Change"]
  = "";

# misc/alerts/user_filter.php3, row 141
$_m["New password"]
  = "";

# misc/alerts/user_filter.php3, row 143
$_m["Retype password"]
  = "";

# misc/alerts/user_filter.php3, row 146
$_m["Change password"]
  = "";

# misc/alerts/user_filter.php3, row 192
$_m["Subscribed Collections"]
  = "";

# misc/alerts/user_filter.php3, row 217
# misc/alerts/util.php3, row 155, 225
$_m["Filter"]
  = "";

# misc/alerts/user_filter.php3, row 218, 256, 285
# misc/alerts/util.php3, row 215
$_m["How often"]
  = "";

# misc/alerts/user_filter.php3, row 221
# misc/alerts/util.php3, row 216
$_m["unsubscribe"]
  = "";

# misc/alerts/user_filter.php3, row 248, 265
$_m["Add"]
  = "";

# misc/alerts/user_filter.php3, row 255
$_m["Add predefined collection"]
  = "";

# misc/alerts/user_filter.php3, row 284
$_m["Add predefined filter"]
  = "";

# misc/alerts/user_filter.php3, row 305
$_m["Sign out"]
  = "";

# misc/alerts/util.php3, row 24
$_m["daily"]
  = "";

# misc/alerts/util.php3, row 25
$_m["weekly"]
  = "";

# misc/alerts/util.php3, row 26
$_m["monthly"]
  = "";

# misc/alerts/util.php3, row 84
$_m["ERROR adding user to alerts_user"]
  = "";

# misc/alerts/util.php3, row 89
$_m["ERROR updating user in alerts_user"]
  = "";

# misc/alerts/util.php3, row 92
$_m["Welcome to APC e-mail alerts"]
  = "";

# misc/alerts/util.php3, row 102
$_m["<p>Hello,</p><p>please confirm your subscription on</p>%1<p>Write the code</p>%2<p>into the box so that we can see you did not subscribe by mistake and your e-mail is working.</p><p>Yours<br>&nbsp; &nbsp; &nbsp;APC Alerts moderators</p>"]
  = "";

# misc/alerts/util.php3, row 144
$_m["Create new collection"]
  = "";

# misc/alerts/util.php3, row 145
$_m["New collection"]
  = "";

# misc/alerts/util.php3, row 147
$_m["Create"]
  = "";

# misc/alerts/util.php3, row 174
$_m["Choose a filter"]
  = "";

# misc/alerts/util.php3, row 204
$_m["Remove filters by setting order to 0."]
  = "";

# misc/alerts/util.php3, row 208
$_m["Update"]
  = "";

# misc/alerts/util.php3, row 209
$_m["Delete"]
  = "";

# misc/alerts/util.php3, row 213
$_m["Collection"]
  = "";

# misc/alerts/util.php3, row 228
$_m["Order"]
  = "";

# misc/alerts/util.php3, row 233
$_m["Add filter"]
  = "";

# admin/alerts_collections.php3, row 52, 58
$_m["Alerts - Collections"]
  = "";

# admin/alerts_collections.php3, row 66
$_m["First create some view of type Alerts Digest and define some filters there."]
  = "";

# admin/alerts_collections.php3, row 94
$_m["Cancel"]
  = "";

# admin/te_alerts_collections.php3, row 39, 45
$_m["Alerts Collections - Email Headers"]
  = "";

?>
