<?php
# $Id$
# Language: JA
# This file was automatically created by the Mini GetText environment
# on 30.9.2002 17:10

# Do not change this file otherwise than by typing translations on the right of =

# Before each message the places where it was used are noted.
# Look there if you are not sure how to translate it.

$mgettext_lang = "ja";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/add_user_collection.php3, row 45
$_m["Error - user was not subscribed"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/add_user_collection.php3, row 52
$_m["Missing required info"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/add_user_collection.php3, row 66
$_m["Howoften set wrong"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/add_user_collection.php3, row 74
$_m["Wrong collection ID"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/add_user_collection.php3, row 101
$_m["You have been successfully subscribed to AA Alerts for %1."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/add_user_collection.php3, row 109
$_m["You must first confirm your subscription (see confirmation e-mail) or subscribe again on %1 in order to receive e-mail Alerts."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/add_user_collection.php3, row 112
# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/alerts.php3, row 210
$_m["You can change your subscriptions on %1."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/alerts.php3, row 181
$_m["AA Alerts - daily digest of "]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/alerts.php3, row 182
$_m["AA Alerts - weekly digest of "]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/alerts.php3, row 183
$_m["AA Alerts - monthly digest of "]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/confirm.php3, row 37
$_m["Congratulations. Your subscription is finished."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/confirm.php3, row 42
$_m["Subscribe to E-mail Alerts"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/confirm.php3, row 47
$_m["Finish your subscription to AA Alerts"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/confirm.php3, row 50
$_m["The code given is not OK. Please try it again. Don't use any spaces."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/confirm.php3, row 54
# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/subscribe.php3, row 57
$_m["Submit"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/index.php3, row 36, 47
$_m["This email is not registered with Alerts."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/index.php3, row 40
$_m["OK. Password was sent."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/index.php3, row 58
$_m["Wrong password."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/index.php3, row 63
$_m["Login to Alerts sending"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/index.php3, row 69
$_m["Login to Personal settings for Alerts sending"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/index.php3, row 79
$_m["New user? Subscribe!"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/index.php3, row 81
# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/subscribe.php3, row 52
$_m["E-mail"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/index.php3, row 83
# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/subscribe.php3, row 54
$_m["Password"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/index.php3, row 86
$_m["Login"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/index.php3, row 87
$_m["Login by your e-mail address. If you don't use password, leave that box empty. If you forgot your password, click here and we will send a new confirmation e-mail to you."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/index.php3, row 87
$_m["Send password"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/user_filter.php3, row 38
$_m["Your session has expired. Please login again."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/user_filter.php3, row 65
$_m["Passwords differ. Please try again."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/user_filter.php3, row 107, 119
$_m["AA Alerts"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/user_filter.php3, row 125
$_m["Welcome, %1"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/user_filter.php3, row 131
$_m["First name"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/user_filter.php3, row 133
$_m["Last name"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/user_filter.php3, row 136
$_m["Change"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/user_filter.php3, row 141
$_m["New password"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/user_filter.php3, row 143
$_m["Retype password"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/user_filter.php3, row 146
$_m["Change password"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/user_filter.php3, row 192
$_m["Subscribed Collections"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/user_filter.php3, row 217
# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 154, 224
$_m["Filter"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/user_filter.php3, row 218, 256, 285
# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 214
$_m["How often"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/user_filter.php3, row 221
# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 215
$_m["unsubscribe"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/user_filter.php3, row 248, 265
$_m["Add"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/user_filter.php3, row 255
$_m["Add predefined collection"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/user_filter.php3, row 284
$_m["Add predefined filter"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/user_filter.php3, row 305
$_m["Sign out"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/subscribe.php3, row 33
$_m["An email with subscription informations was sent to you."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/subscribe.php3, row 37, 43
$_m["Subscribe to AA Alerts"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/subscribe.php3, row 50
$_m["We will send an e-mail message to the address given. Follow the instructions in it to complete your subscription."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 24
$_m["daily"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 25
$_m["weekly"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 26
$_m["monthly"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 85
$_m["ERROR adding user to alerts_user"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 90
$_m["ERROR updating user in alerts_user"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 93
$_m["Welcome to APC e-mail alerts"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 101
$_m["<p>Hello,</p><p>please confirm your subscription by clicking on URL:</p>%1<p>or copy the URL to your web browser so that we can see you did not subscribe by mistake and your e-mail is working.</p><p>Yours<br>&nbsp; &nbsp; &nbsp;APC Alerts moderators</p>"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 143
$_m["Create new collection"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 144
$_m["New collection"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 146
$_m["Create"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 173
$_m["Choose a filter"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 203
$_m["Remove filters by setting order to 0."]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 207
$_m["Update"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 208
$_m["Delete"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 212
$_m["Collection"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 227
$_m["Order"]
  = "";

# /raid/www/htdocs/work.ecn.cz/aa_jakub/misc/alerts/util.php3, row 232
$_m["Add filter"]
  = "";

?>
